"""Admin-added residential complexes — persisted for production deploys."""

ADMIN_COMPLEXES = [
    {
        "name": "Jannat Tower",
        "slug": "jannat-tower",
        "address": "Бишкек, Первомайский р-н, по ул. Логвиненко, д. 3г.",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "3 кв.",
        "completion_year": 2027,
        "price_per_sqm_usd": 1700.0,
        "price_per_sqm_kgs": 148667.0,
        "class_type": "premium",
        "floors": "14",
        "buildings_count": 1,
        "apartments_count": 75,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "/images/jannat-tower.jpg",
        "features": (
            "Расположение в «Золотом квадрате» в самом центре Бишкека. "
            "Клубный формат дома всего на 75 квартир. "
            "Премиальный фасад из натурального гранита. "
            "Закрытая территория с охраной 24/7. Подземный паркинг."
        ),
        "entrances_count": 1,
        "initial_payment_percent": 30.0,
        "installment_months": 15,
        "has_red_book": True,
        "description": (
            "Формат: 1 блок, 1 подъезд, всего 75 квартир. "
            "Фасад из натурального гранита, монолитный каркас."
        ),
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/jannat-tower-legal.docx",
    },
    {
        "name": "LEVAN PARK",
        "slug": "levan-park",
        "address": "Бишкек, Октябрьский р-н, ул. Институт сейсмостойкости строительства-1 (ж/м ИСС), д. 4; д. 2; д. 1а",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "4 кв.",
        "completion_year": 2028,
        "price_per_sqm_usd": 1700.0,
        "price_per_sqm_kgs": 148665.0,
        "class_type": "premium",
        "floors": "От 4 до 12 этажей",
        "buildings_count": 17,
        "apartments_count": 100,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "/images/levan-park.jpg",
        "features": (
            "Премиальный статус локации в районе АУЦА. "
            "Монолитно-кирпичное исполнение. "
            "Каскадная этажность. Подземный паркинг на 300 мест."
        ),
        "entrances_count": 2,
        "initial_payment_percent": 30.0,
        "installment_months": 35,
        "has_red_book": True,
        "description": "17 архитектурных блоков на территории 3,66 га. Сдача в 2027–2028 гг.",
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/levan-park-legal.docx",
    },
    {
        "name": "LEVEL LUX",
        "slug": "level-lux",
        "address": "Бишкек, в Первомайском районе, по ул. Айни  10/1",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "4 кв.",
        "completion_year": 2027,
        "price_per_sqm_usd": 1595.0,
        "price_per_sqm_kgs": 139845.0,
        "class_type": "premium",
        "floors": "14",
        "buildings_count": 2,
        "apartments_count": 168,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "/images/level-lux.jpeg",
        "features": (
            "Этажи 1–8 — кирпич, 9–14 — газоблок D600. "
            "Фасад — керамика Laminam + клинкер. "
            "Домофон с Face ID. Бесшумные лифты."
        ),
        "entrances_count": 1,
        "installment_months": 18,
        "has_red_book": True,
        "description": "168 квартир, премиум-класс, участок 21,62 соток.",
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/level-lux-legal.docx",
    },
    {
        "name": "Аккула",
        "slug": "akkula",
        "address": "Бишкек, Ленинский р-н, по ул. Матыева Э. (бывш. Строительная), д. 21",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "4 кв.",
        "completion_year": 2028,
        "price_per_sqm_usd": 1400.0,
        "price_per_sqm_kgs": 122400.0,
        "class_type": "business",
        "floors": "17",
        "buildings_count": 1,
        "apartments_count": 544,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "",
        "features": (
            "Закрытый двор без машин. Автономная газовая котельная. "
            "Монолитный каркас с кирпичным заполнением. "
            "Панорамное остекление."
        ),
        "initial_payment_percent": 30.0,
        "installment_months": 35,
        "has_red_book": True,
        "description": "544 квартиры. Двухуровневый подземный паркинг на 250 мест.",
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/akkula-legal.pdf",
    },
    {
        "name": "Времена года",
        "slug": "vremena-goda",
        "address": "Бишкек, Октябрьский р-н, ул. А.Токомбаева 27/1.",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "4 кв.",
        "completion_year": 2027,
        "price_per_sqm_usd": 1700.0,
        "price_per_sqm_kgs": 148665.0,
        "class_type": "premium",
        "floors": "от 15 до 24",
        "buildings_count": 4,
        "apartments_count": 100,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "/images/vremena-goda.jpeg",
        "features": (
            "4 башни («сезоны») от 15 до 24 этажей. Потолки 3,6 м. "
            "SPA-зона с бассейном. Закрытый двор с консьержем 24/7."
        ),
        "initial_payment_percent": 30.0,
        "installment_months": 18,
        "has_red_book": True,
        "description": "Премиум-квартал от СК «Елизавета» на Южной магистрали.",
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/vremena-goda-legal.docx",
    },
    {
        "name": "Горизонт",
        "slug": "gorizont",
        "address": "Чуй-ул. Ауэзова",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "2 кв.",
        "completion_year": 2028,
        "price_per_sqm_usd": 1300.0,
        "price_per_sqm_kgs": 113624.0,
        "class_type": "comfort",
        "floors": "16",
        "buildings_count": 4,
        "apartments_count": 378,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "/images/gorizont.jpeg",
        "features": (
            "Монолитно-железобетонный каркас. Кирпич и газоблок. "
            "Панорамное остекление подъездов. Бесшумные лифты."
        ),
        "initial_payment_percent": 15.0,
        "installment_months": 32,
        "has_red_book": True,
        "description": "378 квартир, комфорт+, 4 блока, участок 60 соток.",
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/gorizont-legal.docx",
    },
    {
        "name": "Токио Сити",
        "slug": "tokio-city",
        "address": "Бишкек, Октябрьский р-н, по ул. 7-апреля (бывш. Шабдан баатыра), д. 1а/1 и 160б.",
        "city": "Бишкек",
        "region": "bishkek",
        "status": "building",
        "completion_quarter": "2 кв.",
        "completion_year": 2027,
        "price_per_sqm_usd": 1250.0,
        "price_per_sqm_kgs": 109312.0,
        "class_type": "comfort",
        "floors": "16",
        "buildings_count": 6,
        "apartments_count": 540,
        "verification_score": 0,
        "verification_status": "unverified",
        "image_url": "/images/tokio-city.jpeg",
        "features": (
            "Красная книга. Центральные коммуникации. "
            "Рассрочка до 32 месяцев. Двор без машин, подземный паркинг."
        ),
        "entrances_count": 10,
        "initial_payment_percent": 30.0,
        "installment_months": 35,
        "has_red_book": True,
        "description": "6 блоков по 16 этажей, 540 квартир. Сдача II кв. 2027.",
        "latitude": 42.87,
        "longitude": 74.57,
        "legal_file": "/documents/tokio-city-legal.docx",
    },
]
