services:
  - type: web
    name: chakyruu-kg
    runtime: node
    rootDir: invite-kg
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "20"
